name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: |
        sudo apt-get install texlive-full
        TEXMFHOME=`kpsewhich -var-value=TEXMFHOME`
        mkdir $TEXMFHOME/tex/latex
        git clone https://github.com/daniel-kelley/datasheet $TEXMFHOME/tex/latex
    - name: make pdf
      run: make pdf
    - name: make html
      run: make html
